INSERT INTO APICULTORES(ID_APICULTORES,NOMBRE,NUMERO_APIARIOS,NUMERO_EMPLEADOS,CORREO_ELECTRONICO) VALUES('155Q0277','CRISTHIA ENRIQUE',12,45,'CRISTHYAN_2011@HOTMAIL.COM')

INSERT INTO APICULTORES(ID_APICULTORES,NOMBRE,NUMERO_APIARIOS,NUMERO_EMPLEADOS,CORREO_ELECTRONICO) VALUES('155Q0266','JOSUE',12,45,'JOSUE_2011@HOTMAIL.COM')

INSERT INTO APICULTORES(ID_APICULTORES,NOMBRE,NUMERO_APIARIOS,NUMERO_EMPLEADOS,CORREO_ELECTRONICO) VALUES('155Q0345','OSCAR',12,45,'OSCAR_2011@HOTMAIL.COM')